version: '3.4'

services:
  newsletter.api:
    image: ${DOCKER_REGISTRY-}newsletterapi
    build:
      context: .
      dockerfile: Newsletter.API/Dockerfile
    ports:
      - "5001:443"

  newsletter.reporting.api:
    image: ${DOCKER_REGISTRY-}newsletterreportingapi
    build:
      context: .
      dockerfile: Newsletter.Reporting.Api/Dockerfile
    ports:
        - "6001:443"
         
  newsletter.db:
    image: postgres
    container_name: newsletter.db
    environment:
        - POSTGRES_DB=newsletter
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    ports:
        - 5432:5432
    volumes:
        - ./.containers/newsletter-data:/var/lib/postgresql/data

  newsletter-mq:
    image: rabbitmq:management
    container_name: Newsletter.RabbitMq
    hostname: newsletter-mq
    volumes:
        - ./.containers/queue/data/:/var/lib/rabbitmq
        - ./.containers/queee/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest